name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup deno
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x
